### PR TITLE
Feauter

### PR DESCRIPTION
**Pull request by Hasinarahman**
this is new project for survey form.
first I created new repo
then clone the repo in VS code 
create index file and style file 
uplod the linter files 
push the working in github.

### CODE REVIEW

**Comment by ahzamir** [comment]
Hey @Hasinarahman ,
- As I can see you have styling linters issues please solve them first so I can provide you feedback on your project.

**Comment by Hasinarahman** [comment]
@ahzamir 
Hello sir, I solved the linter issues please check the code and give me feedback.

**Comment by ahzamir** [comment]
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Hasinarahman** [comment]
Hi sir.
 I did  my project  to the freecodecamp website survey form project and I solved the missing requirements.
So I will be happy if you review my project. 
**@ahzamir**

**Comment by Hasinarahman** [comment]
Hi sir.
I did my project to the freecodecamp website survey form project and I solved the missing requirements.
So I will be happy if you review my project.
@Ahzia

**Review by ahzia — APPROVED** [review]
### Hi @Hasinarahman  🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Share your First Project on your LinkedIn account and add a proud moment text on it with a screenshot.
- Suggestion: Your pull request title is not descriptive, it should be a short title that can explain what the pull request is about ex: FreecodeCamp Surevy Form
# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WellDoneGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
❌ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
